### PR TITLE
Fulfill conditions of sale when the apartment's housing company is released from regulation.

### PR DESCRIPTION
**Pull request by matti-lamppu**
# Hitas Pull Request

# Description

Fulfill conditions of sale when the apartment's housing company is released from regulation.

## Pull request checklist

Check the boxes for each DoD item that has been completed:

- **Testing**
  - [x] Changes have been tested
  - [x] Automatic tests have been added
- **Database**
  - [ ] Database migrations will work in the DEV & TEST environments
  - [ ] initial.json has been updated to work with migrations
  - [ ] Oracle migration has been updated
- **Documentation**
  - [ ] Tooltips have been added in the frontend for all new fields
  - [ ] OpenAPI definitions have been updated
  - [ ] Test instructions have been written for the customer in the appropriate ticket in Jira
  - [ ] Terminology page in Confluence has been updated

## Test plan

- [x] Automated tests

## Tickets

This pull request resolves all or part of the following ticket(s): HT-574

### CODE REVIEW

**Review by ranta — APPROVED** [review]
As HousingCompany regulation state can also be changed directly through the API _('housing company edit page' and 'Manually release housing company' in 30 year regulation)_, maybe we should add some logic to the API update requests too? 🤔

**Comment by matti-lamppu** [comment]
Added logic for calling `fulfill_conditions_of_sales_for_housing_companies` in the housing company update endpoint. Both the housing company edit page and thirty-year regulation released by plot department function should use this endpoint.

**Comment by matti-lamppu** [comment]
Made updating improvements optional, since when the housing company update endpoint is used to manually update regulation status on to released by the plot department, the frontend doesn't need to know the state of improvements at that time.

**Review by ranta — COMMENTED** [review]
> Make improvements optional in housing company update (and create)

I think this goes against common good practices a little bit, would it be more sensible to  use PATCH instead of PUT with optional fields? 🤔

**Comment by matti-lamppu** [comment]
I'll have to duplicate some code to add a patch method, but it can be done.

**Review by ranta — APPROVED** [review]
🐍

**Pull request merged**
