### PR TITLE
Remove address from property manager, make email accept empty string

### PR DESCRIPTION
**Pull request by matti-lamppu**
# Hitas Pull Request

# Description

Removes address information from property manager. 

## Pull request checklist

Check the boxes for each DoD item that has been completed:

- **Testing**
  - [x] Changes have been tested
  - [x] Automatic tests have been added
- **Database**
  - [x] Database migrations will work in the DEV & TEST environments
  - [ ] initial.json has been updated to work with migrations
  - [ ] Oracle migration has been updated
- **Documentation**
  - [ ] Tooltips have been added in the frontend for all new fields
  - [x] OpenAPI definitions have been updated
  - [ ] Test instructions have been written for the customer in the appropriate ticket in Jira
  - [ ] Terminology page in Confluence has been updated

## Test plan

- [x] Automated tests

## Tickets

This pull request resolves all or part of the following ticket(s): HT-683

### CODE REVIEW

**Comment by matti-lamppu** [comment]
Conflicting migration with #364, so only merge this it that one.

**Review by ranta — APPROVED** [review]
🦬

**Comment by matti-lamppu** [comment]
@ranta Added email filter to property manager endpoint from a request from @annisassi, can you review this?

**Review by ranta — APPROVED** [review]
Email filter addition was a trivial change, would have been fine to just merge 😛

**Pull request merged**
