### PR TITLE
Apartment improvements

### PR DESCRIPTION
**Pull request by ranta**
Frontend:
- List apartment and housing company improvements in details pages
- Add a page to create and edit apartment improvements
- Various bugfixes
- More generic components! 😄 

Backend:
- Add more data to initial.json
- Add Django admins for improvements

### CODE REVIEW

**Review by vincit-matu — APPROVED** [review]
🤟

**Review by toikarin-vincit — COMMENTED** [review]
Few notes:
 - improvements lists are now working when selecting the apartment from housing company, not by apartment search
 - apartment search is broken(?)
 - adding improvements says `päivä` when a month is expected. also no help for formatting it
 - empty improvement lists look a bit strange :)

**Comment by ranta** [comment]
> -  improvements lists are now working when selecting the apartment from housing company, not by apartment search
> - apartment search is broken(?)
They are working fine for me locally 🤔 
(Going to an apartment page `/apartments` url, there shouldn't be a difference in where you navigate to the page from)

> - adding improvements says päivä when a month is expected. also no help for formatting it
Fixed the labels and added a help text for the format :)

> - empty improvement lists look a bit strange :)
Added a check for this as well :)

**Review by toikarin-vincit — APPROVED** [review]
:rocket:

**Pull request merged**
