### PR TITLE
Add job performance to max price pdf downloads

### PR DESCRIPTION
**Pull request by matti-lamppu**
# Hitas Pull Request

# Description

Makes downloading confirmed/unconfirmed max price PDFs create job performance objects. 

> Frontend changes to include `request_date` on these endpoints are necessary to make this work!

## Pull request checklist

Check the boxes for each DoD item that has been completed:

- **Testing**
  - [x] Changes have been tested
  - [x] Automatic tests have been added
- **Database**
  - [ ] Database migrations will work in the DEV & TEST environments
  - [ ] initial.json has been updated to work with migrations
  - [ ] Oracle migration has been updated
- **Documentation**
  - [ ] Tooltips have been added in the frontend for all new fields
  - [x] OpenAPI definitions have been updated
  - [ ] Test instructions have been written for the customer in the appropriate ticket in Jira
  - [ ] Terminology page in Confluence has been updated

## Test plan

- [x] Automated tests
- [ ] Download max price PDFs (manually before frontend is updated) and observe the job performance objects in the database

## Tickets

This pull request resolves all or part of the following ticket(s): HT-514, HT-515, HT-567

### CODE REVIEW

**Comment by matti-lamppu** [comment]
@vincit-matu frontend changes can be included in this PR, I think? Otherwise, ninja will break for PDFs when this PR is merged.

**Review by ranta — COMMENTED** [review]
Seems to be working perfectly, but requires rebasing on `master` due to conflicts

---

Improvement suggestion:
Right now the same PDF can be downloaded multiple times, and every time a `JobPerformance` object is created. To me it doesn't make sense to record if same file again and again would.
To reduce the amount of duplicate data I would add some sort of limiter to the objects created, e.g. Unique Together (User, Apartment, Date, Source).

**Comment by matti-lamppu** [comment]
We didn't talk about limiting the creation of job performances in any way, so I left it like that. Might be work talking to the customer about it before deciding anything.

**Review by ranta — APPROVED** [review]
Let's wait for all commits related to this ticket to be merged to a same branch before merging to master :)

**Pull request merged**
